# Generated by Django 4.2.1 on 2023-05-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('language', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('vat_number', models.CharField(max_length=20)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_address', models.CharField(max_length=255)),
                ('company_postcode', models.CharField(max_length=10)),
                ('company_city', models.CharField(max_length=255)),
                ('company_country', models.CharField(max_length=255)),
                ('billing_same_as_company', models.BooleanField(default=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('billing_city', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_country', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
