# Generated by Django 4.2.1 on 2023-05-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vrijstaand', 'Vrijstaand woning'), ('studio', 'Studio Appartement'), ('rijwoning', 'Rijwoning / Duplex / halfopen'), ('opbrengsteigendom', 'OpbrengstEigendom'), ('bouwgrond', 'Bouwgrond'), ('bedrijfspand', 'Bedrijfspand')], max_length=20)),
                ('land', models.CharField(default='Belgie', max_length=100)),
                ('straatnaam', models.CharField(max_length=100)),
                ('huisnummer', models.CharField(max_length=10)),
                ('toevoeging', models.CharField(blank=True, max_length=50)),
                ('postcode', models.CharField(max_length=20)),
                ('plaats', models.CharField(max_length=50)),
                ('gebruiksoppervlakte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oppervlakteBijgebouwen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perceel', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
