# Generated by Django 4.2.1 on 2023-05-28 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
