# Generated by Django 4.2.1 on 2023-05-29 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.customer'),
        ),
        migrations.AddField(
            model_name='property',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Pending', 'Bezig'), ('Editing', 'Editing'), ('Delivered', 'Geleverd')], default='Pending', max_length=200, null=True),
        ),
    ]
