# Generated by Django 4.2.1 on 2023-05-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_property_customer_property_date_created_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Order',
        ),
    ]
