# Generated by Django 4.2.1 on 2023-06-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_customer_familyname_customer_prefix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=200, null=True)),
                ('vat', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('zip', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('billing_company_name', models.CharField(max_length=200, null=True)),
                ('billing_vat', models.CharField(max_length=200, null=True)),
                ('billing_adr', models.CharField(max_length=200, null=True)),
                ('billing_zip', models.CharField(max_length=200, null=True)),
                ('billing_city', models.CharField(max_length=200, null=True)),
                ('billing_country', models.CharField(max_length=200, null=True)),
                ('billing_email', models.EmailField(max_length=200, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.customer')),
            ],
        ),
    ]
