# Generated by Django 4.2.1 on 2023-06-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_getkeyschoice_keychoice_ordertype_service_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getkeyschoice',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.company'),
        ),
    ]
