# Generated by Django 4.2.1 on 2023-06-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_deliveryrecipient_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.deliveryrecipient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.invoicerecipient'),
        ),
    ]
