# Generated by Django 4.2.1 on 2023-06-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_order_delivery_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_recipient',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_recipient',
            field=models.ManyToManyField(to='projects.deliveryrecipient'),
        ),
    ]
