# Generated by Django 4.2.1 on 2023-06-11 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_order_delivery_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetKeysLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_keys_choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='get_keys_adr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='get_keys_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='get_keys_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='get_keys_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='get_keys_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='get_keys_zip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='get_keys_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.getkeyslanguage'),
        ),
    ]
