# Generated by Django 4.2.1 on 2023-06-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_getkeyslanguage_order_get_keys_adr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getkeyslanguage',
            old_name='get_keys_choice',
            new_name='get_keys_language',
        ),
    ]
