# Generated by Django 4.2.1 on 2023-06-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_order_rec_email_order_rec_email_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='get_keys_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.getkeyslanguage'),
        ),
    ]
