# Generated by Django 4.2.1 on 2023-06-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_company_get_keys_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
    ]
