# Generated by Django 4.2.1 on 2023-06-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_country_company_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='land',
        ),
    ]
