# Generated by Django 4.2.1 on 2023-06-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_order_inv_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
